server_tokens off;

limit_req_zone $binary_remote_addr zone=rainwave_general:10m rate=20r/s;
limit_conn_zone $binary_remote_addr zone=rainwave_per_ip:10m;

upstream rainwave_app {
    server unix:/run/rainwave/gunicorn.sock fail_timeout=0;
    keepalive 8;
}
